### ISSUE TITLE
Can't find element when source document contain an xsd

### ISSUE THREAD

**Issue by matthew-b-payne** [morou/gulp-xml-editor#1]
Take document: 

<?xml version="1.0" encoding="UTF-8"?>
<widget >
  <name>this is name</name>
  <version major="1" minor="0"></version>
</widget>

gulp.task('xmlmod', function() {
gulp.src("./text.xml")
  .pipe(xeditor([
    {path: '//name', text: 'new names2'},
    {path: '//version', attr: {'major': '2'}}
  ]))
  .pipe(gulp.dest("./dest"));
});

Works !!!

Change document to:

<?xml version="1.0" encoding="UTF-8"?>
<widget id="com.sutternow.hotpaytato" version="0.0.11" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" >
  <name>this is name</name>
  <version major="1" minor="0"></version>
</widget>

The task then errors with: 

Error in plugin 'gulp-xml-editor'
Can't find element at "//widget"
    at D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\index.js:20:26
    at Array.forEach (native)
    at editByObject (D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\index.js:17:12)
    at Transform._transform (D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\index.js:64:34)
    at Transform._read (D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:184:10)
    at Transform._write (D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:172:12)
    at doWrite (D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:237:10)
    at writeOrBuffer (D:\exp\ionic-cordova-seed\node_modules\gulp-xml-editor\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:227:5)

**Comment by wendellpalazzo** [comment]
Hi.. i have problem usign config.xml in ionicframework project.. 

this is the original:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="app.testing" version="0.0.21" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
<name>myAppName</name>

```

using this the gulp script failed with this errors:
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Can't find element at "//name"

without the attributes : xmlns e xmlns:cdv.... works Fine!
`<widget id="app.testing" version="0.0.21">`

Can you help me?
